apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exampleclaim # The PVC name will be used in a Pod configurations when mounting this volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd # The name of the volume declared under volumes 
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: exampleclaim  # Name of our PVC
